name: CD
on:
  push:
    branches:
      - master
    paths:
      - '**.css'
      - '**.html'
      - '**.png'
      - '**.vue'
      - '**.js'
      - '**.svg'
      - '**.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Build
        run: npm run build
      - name: Generate static files
        run: npm run generate
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Upload files to storage account
        uses: azure/CLI@v1
        with:
          azcliversion: 2.11.1
          inlineScript: az storage blob sync --source dist --container '$web' --account-name websitesquiddymabob